name: mahafez_core
description: Layer 1 Core/Platform Pure Dart Foundation for Mahafez Platform.
version: 1.0.0
repository: https://github.com/mahafez-app/mahafez_core
publish_to: 'none'

environment:
  sdk: ^3.13.3

dependencies:
  equatable: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
